---
title: "git_00"
author: "Giselle Gonzalez"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  
  
Beware the Jabberwock, my son!  
      The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun  
      The frumious Bandersnatch!”  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

He halted in the wind, and - what was that  
Far in the maples, pale, but not a ghost?  
He stood there bringing March against his thought,  
And yet too ready to believe the most.  

"Oh, that's the Paradise-in-bloom," I said; 
 

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
      Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I love your hands:  
They are big hands, firm hands, gentle hands;  
Hair grows on the back near the wrist….  
I have seen the nails broken and stained  
From Hard work.  
And yet, when you touch me,  
I grow small……and quiet……  
……..And happy……..  
If I might only grow small enough  
To curl up into the hollow of your palm,  
Your left palm,  
Curl up, lie close and cling,  
So that I might know myself always there,  
……Even if you forgot.  









